// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var topNodeOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--no-headers", Description: "If present, print output without headers"},
	prompt.Suggest{Text: "-l", Description: "Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2). Matching objects must satisfy all of the specified label constraints."},
	prompt.Suggest{Text: "--selector", Description: "Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2). Matching objects must satisfy all of the specified label constraints."},
	prompt.Suggest{Text: "--show-capacity", Description: "Print node resources based on Capacity instead of Allocatable(default) of the nodes."},
	prompt.Suggest{Text: "--sort-by", Description: "If non-empty, sort nodes list using specified field. The field can be either 'cpu' or 'memory'."},
	prompt.Suggest{Text: "--use-protocol-buffers", Description: "Enables using protocol-buffers to access Metrics API. Usage:\n  kubectl top node [NAME | -l label] [options] Use \"kubectl options\" for a list of global command-line options (applies to all commands)."},
}
