// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var configSetOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--set-raw-bytes", Description: "When writing a []byte PROPERTY_VALUE, write the given string directly without base64 decoding. Usage:\n  kubectl config set PROPERTY_NAME PROPERTY_VALUE [options] Use \"kubectl options\" for a list of global command-line options (applies to all commands)."},
}
