// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/c-bata/go-prompt"
)

var configGetContextsOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--no-headers", Description: "When using the default or custom-column output format, don't print headers (default print headers)."},
	prompt.Suggest{Text: "-o", Description: "Output format. One of: (name). Usage:\n  kubectl config get-contexts [(-o|--output=)name)] [options] Use \"kubectl options\" for a list of global command-line options (applies to all commands)."},
	prompt.Suggest{Text: "--output", Description: "Output format. One of: (name). Usage:\n  kubectl config get-contexts [(-o|--output=)name)] [options] Use \"kubectl options\" for a list of global command-line options (applies to all commands)."},
}
